name: Lint and Test Before Merge
on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - development
jobs:
  test:
    environment: test
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      DB_HOST: roundhouse.proxy.rlwy.net
      DB_NAME: railway
      DB_PASSWORD: FB3-C-cBE261Gcaab*66352bdgB5d212
      DB_PORT: 36206
      DB_USERNAME: postgres
      IMAGEKIT_PUBLIC_KEY: public_DVITNf+5XTiO9Y3dKRqIlhuE58Q=
      IMAGEKIT_PRIVATE_KEY: private_fNqHqD5ocFxgaoj8uWVeiJdXf9s=
      IMAGEKIT_URL_ENDPOINT: https://ik.imagekit.io/dpmd80fxd
      AUTH_EMAIL: jacksparrow133333@gmail.com
      AUTH_PASSWORD: ofwf sdep whgd mrbt
      PORT: 3000
      JWT_SECRET: rahasia
      JWT_EXPIREDIN: 1d
      PASSWORD_HASH: admin123
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: drop existing DB
        run: npm run db:drop
      - name: Create DB
        run: npm run db:create
      - name: Migration database
        run: npm run db:migrate
      - name: Seed database
        run: npm run db:seed
      - name: Test code
        id: run-tests
        run: npm run test
  lint:
    needs: test
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
  merge:
    needs: [test, lint]
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        run: echo "Can Be Merge..."
  report:
    needs: merge
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Something went wrong"
          echo "${{ toJSON(github) }}"
