const { v4: uuidv4 } = require('uuid')

module.exports = (courseId) => [
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[0].id,
    totalDuration: 95,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai Frontend',
    courseId: courseId[0].id,
    totalDuration: 125,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[1].id,
    totalDuration: 80,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai UI/UX design',
    courseId: courseId[1].id,
    totalDuration: 95,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[2].id,
    totalDuration: 120,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai bahasa assembly x86',
    courseId: courseId[2].id,
    totalDuration: 60,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 3,
    name: 'Membuat aplikasi android menggunakan asembly x86',
    courseId: courseId[2].id,
    totalDuration: 120,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[3].id,
    totalDuration: 120,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Membuat Restful API dengan C',
    courseId: courseId[3].id,
    totalDuration: 80,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[4].id,
    totalDuration: 40,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai Backend dengan Golang',
    courseId: courseId[4].id,
    totalDuration: 120,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[5].id,
    totalDuration: 50,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai Android Studio',
    courseId: courseId[5].id,
    totalDuration: 70,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[6].id,
    totalDuration: 90,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai UI/UX design',
    totalDuration: 80,
    courseId: courseId[6].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[7].id,
    totalDuration: 65,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai UI/UX design',
    courseId: courseId[7].id,
    totalDuration: 105,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[8].id,
    totalDuration: 65,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai Product Management',
    courseId: courseId[8].id,
    totalDuration: 95,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[9].id,
    totalDuration: 65,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai iOS dengan Swift',
    courseId: courseId[9].id,
    totalDuration: 80,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[10].id,
    totalDuration: 65,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai Data Science',
    courseId: courseId[10].id,
    totalDuration: 105,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 1,
    name: 'Pendahuluan',
    courseId: courseId[11].id,
    totalDuration: 50,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    no: 2,
    name: 'Memulai Android dengan Android Studio',
    courseId: courseId[11].id,
    totalDuration: 85,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
