const { v4: uuidv4 } = require('uuid')

module.exports = (chapterId) => [
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    chapterId: chapterId[0].id,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[0].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[0].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[1].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[1].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 6',
    id: uuidv4(),
    no: 6,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[1].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 7',
    id: uuidv4(),
    no: 7,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[1].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[2].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[2].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[2].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[3].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[3].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 6',
    id: uuidv4(),
    no: 6,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[3].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[4].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[4].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[4].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[5].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[5].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 6',
    id: uuidv4(),
    no: 6,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[5].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 7',
    id: uuidv4(),
    no: 7,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[6].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 8',
    id: uuidv4(),
    no: 8,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[6].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 9',
    id: uuidv4(),
    no: 9,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[6].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[7].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[7].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[7].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[8].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[8].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 6',
    id: uuidv4(),
    no: 6,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[8].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[9].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[9].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[10].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[10].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[10].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[11].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[11].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[12].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[12].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[12].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[13].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[13].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[14].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[14].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[14].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[15].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[15].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[16].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[16].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[16].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[17].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[17].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[18].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[18].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[18].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[19].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[19].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[20].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[20].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[20].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[21].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[21].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[22].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[22].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[22].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 1',
    id: uuidv4(),
    no: 1,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-30-seconds.mp4?updatedAt=1701743051234',
    duration: 30,
    chapterId: chapterId[23].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 2',
    id: uuidv4(),
    no: 2,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[23].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 3',
    id: uuidv4(),
    no: 3,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[24].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 4',
    id: uuidv4(),
    no: 4,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-20-seconds?updatedAt=1701742975944',
    duration: 20,
    chapterId: chapterId[24].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'video 5',
    id: uuidv4(),
    no: 5,
    videoUrl:
        'https://ik.imagekit.io/96gmelvyq/dummy-45-seconds.mp4?updatedAt=1701743051370',
    duration: 45,
    chapterId: chapterId[24].id,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
